// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyeflkukcdqsufsbgpgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5ZWZsa3VrY2Rxc3Vmc2JncGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NTMyMTgsImV4cCI6MjA4ODAyOTIxOH0.li7rhfgrhCg1eJ8QZLHMkxQEPaOF8u2BJ7Yo1cUAde0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});