// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbnpquaskwncjmlmtqio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNibnBxdWFza3duY2ptbG10cWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNTAxOTMsImV4cCI6MjA4MDkyNjE5M30.KxyIFrWwH-0bTmuI8IAjw7Wh5Owp7rUPvYRINHT8Kpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
