// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juxcadksfsormxvivhdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eGNhZGtzZnNvcm14dml2aGR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3OTk1MDksImV4cCI6MjA5NjM3NTUwOX0.8C3dHt0fKGN8FNxSRNimZzGGHKtOgaOC-dIRpI3De14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});